version: '3.8'

services:
  postgres:
    image: postgres:16.9
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./data/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
     

  redis:
    image: redis:7.2-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  flask:
    build: .
    container_name: flask_app
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      # Point SQLAlchemy to the Docker network alias "db"
      DATABASE_URL: ${DATABASE_URL:-postgresql://myuser:mypassword@postgres:5432/mydatabase}
      # (Optional) override cache URL if your config reads REDIS_URL
    volumes:
      - .:/app
    entrypoint: ["/app/entrypoint.sh"]


volumes:
  db-data:
  redis-data:
