name: GitHub Actions Demo
run-name: Run Tests
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres to be ready..."
          while ! pg_isready -h localhost -p 5432 -U postgres; do
            sleep 1
          done
          echo "Postgres is ready!"
      - name: Initialize Postgres schema
        env:
          PGPASSWORD: ${{ vars.TEST_POSTGRES_PASSWORD }}
        run: |
          psql -h localhost -p 5432 -U postgres -d test_db -f data/init_db.sql
      - name: Set up Python test
        uses: actions/setup-python@v5
        with:
          # Set up Python version. The architecture is set to x64 by default.
          python-version: "3.11"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        env:
          TEST_REDIS_URL: ${{ vars.TEST_REDIS_URL }}
          TEST_POSTGRES_URL: ${{ vars.TEST_POSTGRES_URL }}
        run: |
          pytest -q
