name: GitHub Actions Demo
run-name: Run Tests
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: ${{ env.TEST_POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.TEST_POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.TEST_POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=5
    env:
      REDIS_URL: ${{ secrets.TEST_REDIS_URL }}
      POSTGRES_URL: ${{ secrets.TEST_POSTGRES_URL }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Set up Python test
        uses: actions/setup-python@v5
        with:
          # Set up Python version. The architecture is set to x64 by default.
          python-version: "3.11"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest -q
